/**
 * DearMe lockdown layer — SKILL.md generator.
 *
 * Provenance: ported from `clawdbob/src/lockdown/skill-template.js`.
 * The moat clause is rephrased for DearMe's product surface, but the
 * mechanism (deny direct LLM provider calls, force the DearMe proxy) is
 * identical to the verified Polsia production layer.
 */

import {
  DEARME_LOCKDOWN_VERSION,
  type DearMeLockdownInput,
} from "./settings-template.js";

export const DEARME_LOCKDOWN_MOAT_CLAUSE =
  "NEVER call LLM providers directly. ONLY use DearMe API endpoints.";

export function skillForDearMeUser(input: DearMeLockdownInput): string {
  const now = (input.now ?? (() => new Date()))();
  const proxy = input.dearMeProxyUrl;
  return `# DearMe Operating Constraints

## CRITICAL — AI access

${DEARME_LOCKDOWN_MOAT_CLAUSE}

- ❌ Do NOT add @anthropic-ai/sdk, openai, langchain, @aws-sdk/client-bedrock, or similar packages
- ❌ Do NOT make HTTP calls to api.openai.com, api.anthropic.com, bedrock-runtime.*.amazonaws.com, or any other LLM provider
- ❌ Do NOT store provider API keys (OpenAI, Anthropic, Google, AWS, etc.) in this workspace or its env

✅ All AI calls go through DearMe's proxy:
- OpenAI-compatible chat: \`${proxy}/ai/openai/v1/chat/completions\`
- Anthropic-compatible messages: \`${proxy}/api/proxy/ai/v1/messages\`
- Voice gate: \`${proxy}/v1/voice/score\`
- Approval resolver: \`${proxy}/v1/approvals\`

The DearMe proxy handles billing, voice-gate scoring, per-task cost attribution,
model routing, and fallback. Bypassing it breaks the voice gate and the cost
attribution that keeps DearMe sustainable for the user.

## Other constraints

- Do not run \`git push\`, \`git remote add\`, \`git remote set-url\` — DearMe handles deploys via \`deploy_site\`
- Do not run \`sudo\`, \`rm -rf /\`, or other destructive commands
- Do not exfiltrate via \`curl api.github.com\`, \`curl api.openai.com\`, \`curl api.anthropic.com\`, or wget equivalents
- Sandbox mode is enabled in \`.claude/settings.json\` — respect it
- Do not publish packages: \`npm publish\`, \`yarn publish\`, \`pip install\` are denied

## User

- handle: \`${input.userHandle}\`
- DearMe proxy: \`${proxy}\`
- Lockdown version: ${DEARME_LOCKDOWN_VERSION}
- Generated: ${now.toISOString()}

This file is auto-generated by the DearMe OpenClaw plugin. Edits will be
overwritten on next plugin sync.
`;
}
