import fs from "node:fs/promises";
import path from "node:path";
import { describe, expect, it } from "vitest";

const repoRoot = path.basename(process.cwd()) === "server"
  ? path.resolve(process.cwd(), "..")
  : process.cwd();

const backendAdminCopySources = [
  "server/src/worktree-config.ts",
  "server/src/services/environments.ts",
  "server/src/services/adapter-plugin-store.ts",
  "server/src/services/company-skills.ts",
  "server/src/routes/plugins.ts",
  "packages/adapters/claude-local/src/server/quota.ts",
  "packages/adapters/codex-local/src/server/codex-args.ts",
  "server/src/services/company-portability.ts",
];

const staleBackendAdminCopy = [
  "# Paperclip environment variables",
  "# Generated by Paperclip worktree repair",
  "Default execution environment for Paperclip runs on this machine.",
  "Managed directory for Paperclip external adapter plugins. Do not edit manually.",
  "Paperclip bundled",
  "Paperclip workspace",
  "Paperclip dashboard",
  "Paperclip plugin API surface",
  "Paperclip could not load subscription quota data",
  "Paperclip will ignore it for model",
  "Paperclip will import the routine trigger without those limits.",
];

describe("backend admin user-facing copy", () => {
  it("keeps default environment, plugin, skill-source, and admin warnings DearMe-facing", async () => {
    const sources = await Promise.all(
      backendAdminCopySources.map(async (sourcePath) => ({
        sourcePath,
        source: await fs.readFile(path.join(repoRoot, sourcePath), "utf8"),
      })),
    );

    for (const { sourcePath, source } of sources) {
      for (const stalePhrase of staleBackendAdminCopy) {
        expect(source, `${sourcePath} should not expose "${stalePhrase}"`).not.toContain(stalePhrase);
      }
    }

    const combinedSource = sources.map(({ source }) => source).join("\n");
    expect(combinedSource).toContain("# DearMe environment variables");
    expect(combinedSource).toContain("# Generated by DearMe worktree repair");
    expect(combinedSource).toContain("Default execution environment for DearMe runs on this machine.");
    expect(combinedSource).toContain("Managed directory for DearMe external adapter plugins. Do not edit manually.");
    expect(combinedSource).toContain("DearMe bundled");
    expect(combinedSource).toContain("DearMe workspace");
    expect(combinedSource).toContain("DearMe dashboard");
    expect(combinedSource).toContain("DearMe plugin API surface");
    expect(combinedSource).toContain("DearMe could not load subscription quota data");
    expect(combinedSource).toContain("DearMe will ignore it for model");
    expect(combinedSource).toContain("DearMe will import the routine trigger without those limits.");
  });
});
