import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const testDir = path.dirname(fileURLToPath(import.meta.url));
const cliSrcDir = path.resolve(testDir, "..");

const sourceFiles = [
  "client/http.ts",
  "index.ts",
  "commands/onboard.ts",
  "commands/run.ts",
  "commands/allowed-hostname.ts",
  "commands/auth-bootstrap-ceo.ts",
  "commands/client/common.ts",
  "commands/client/context.ts",
  "commands/client/agent.ts",
  "commands/client/company.ts",
  "commands/env-lab.ts",
  "commands/routines.ts",
  "commands/worktree.ts",
  "checks/agent-jwt-secret-check.ts",
  "checks/deployment-auth-check.ts",
  "config/env.ts",
];

const staleUserFacingPhrases = [
  "Could not reach the Paperclip API.",
  "Paperclip server is not running",
  "before it reaches Paperclip",
  "Start Paperclip with",
  "If Paperclip is running elsewhere",
  "Paperclip data directory root",
  "Paperclip CLI",
  "Start Paperclip immediately",
  "Paperclip setup",
  "Paperclip server API",
  "Paperclip config file",
  "Existing Paperclip install",
  "Start Paperclip now?",
  "Existing Paperclip setup",
  "Starting Paperclip server",
  "Paperclip dev server",
  "Paperclip server entrypoint",
  "Paperclip server failed",
  "Restart the Paperclip server",
  "start the Paperclip server",
  "Generated by Paperclip CLI commands",
  "Paperclip skills",
  "Select what Paperclip should import",
  "Paperclip instance id (default: current/default)",
  "worktree-local Paperclip instance",
  "Run Paperclip inside this repo",
  "start Paperclip once",
  "Paperclip worktree",
  "Paperclip worktrees",
  "Source and target Paperclip configs",
  "Stop Paperclip in",
  "isolated Paperclip DB",
  "Worktree-local Paperclip instance helpers",
  "isolated Paperclip instance",
  "current worktree-local Paperclip instance",
  "another Paperclip instance or worktree",
  "linked worktree-local Paperclip instance",
];

function readCliCopySources(): string {
  return sourceFiles
    .map((relativePath) => fs.readFileSync(path.join(cliSrcDir, relativePath), "utf8"))
    .join("\n\n");
}

describe("CLI user-facing copy", () => {
  it("keeps setup, run, API, and local-skill guidance DearMe-facing", () => {
    const source = readCliCopySources();

    for (const phrase of staleUserFacingPhrases) {
      expect(source).not.toContain(phrase);
    }

    expect(source).toContain("Could not reach the DearMe API.");
    expect(source).toContain("DearMe data directory root");
    expect(source).toContain("DearMe CLI");
    expect(source).toContain("Existing DearMe install");
    expect(source).toContain("Starting DearMe server");
    expect(source).toContain("DearMe runtime skills");
    expect(source).toContain("Select what DearMe should import");
    expect(source).toContain("DearMe instance id (default: current/default)");
    expect(source).toContain("worktree-local DearMe instance");
    expect(source).toContain("Run DearMe inside this repo");
    expect(source).toContain("isolated DearMe DB");
    expect(source).toContain("Worktree-local DearMe instance helpers");
  });
});
